### ISSUE TITLE
Can't replicate the tutorial

### ISSUE THREAD

**Issue by mheiser-md** [topherconley/optimize-it#1]
Hi,

not sure if this is still maintained, but I'll give it a shot :)
reran` your script (as in the Rnw file) like this:

``` r
library(xcms) #massifquant (make sure mzR and Rcpp are under same version build)
library(xtable) #latex table generation
library(signal) #savitsky-golay filtering
library(pdist) #euclidean distance between two matrices 
mouse_file <- "<absolute path to>/optimize-it/mouse_data/mouse_5500_7250_600_637.mzML"
data_mouse = xcmsRaw(filename = mouse_file)
image(data_mouse)

ixs = xcmsSet(files = mouse_file, method = "massifquant", prefilter = c(1, 6.5e4), peakwidth = c(15, 100),ppm = 25,  criticalValue = 1.5, consecMissedLimit = 2, withWave = 0)

ithreshold = seq(from = 6.5e4, to = 1.5e5, length = 5)
idetect = lapply(ithreshold, function(t) which(ixs@peaks[, "into"] >= t))
names(idetect) = paste0("ithresh", ithreshold)
ndetect = sapply(idetect, length)
plot(ithreshold, ndetect, pch  = 19, type = 'o', xlab = "intensity threshold", ylab  = "IT detected")
```

Unfortunetaly the filter thresholds produced this graph:

![image](https://cloud.githubusercontent.com/assets/13658867/13102914/171d4914-d552-11e5-8a52-ef443768d763.png)

As opposed to this:

![image](https://cloud.githubusercontent.com/assets/13658867/13102970/688999ec-d552-11e5-860b-45750735f949.png)

I can roughly replicate this plot if I increase the threshold to 1.5e7 instead of 1.5e5, however I then can't find any more peaks with xcmsSet if I update the threshold. 
Did something in the xcms or massifquant code change over the years that could've caused this?

Here is my session info:

``` r
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pdist_1.2           signal_0.7-6        xtable_1.8-0        xcms_1.46.0         Biobase_2.30.0      ProtGenerics_1.2.1  BiocGenerics_0.16.1
[8] mzR_2.4.0           Rcpp_0.12.2        

loaded via a namespace (and not attached):
[1] MASS_7.3-45        tools_3.2.1        RColorBrewer_1.1-2 codetools_0.2-14   grid_3.2.1         lattice_0.20-31 
```

**Comment by topherconley** [comment]
Thank you for your interest and pointing this out :+1:

The tutorial should now be reproducible. The problem was I had (for some reason unclear to me) switched thresholding to the area under the curve instead of the maximum intensity after compiling the pdf.  The latest commit highlights the change. If you still experience problems/questions please don't hesitate to contact me.
